apiVersion: v1
kind: Service
metadata:
  name: complete-production-ec2-service
  labels:
    app: dinesh-mistry-app
spec:
  selector:
    app: dinesh-mistry-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP