apiVersion: v1
kind: Service
metadata:
  name: {{ include "complete-production-e2e-dinesh-mistry.fullname" . }}
  labels:
    {{- include "complete-production-e2e-dinesh-mistry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "complete-production-e2e-dinesh-mistry.selectorLabels" . | nindent 4 }}
